##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  archlinux:
    # Useful URL: https://git.archlinux.org/svntogit/community.git/tree/mate-system-monitor
    - autoconf-archive
    - clang
    - gcc
    - git
    - gtkmm3
    - libgtop
    - libwnck3
    - make
    - mate-common
    - mate-desktop
    - which
    - yelp-tools

  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-mate-team/mate-system-monitor
    - autopoint
    - autoconf-archive
    - clang
    - clang-tools
    - cppcheck
    - gcc
    - g++
    - git
    - libglib2.0-dev
    - libglibmm-2.4-dev
    - libgtk-3-dev
    - libgtkmm-3.0-dev
    - libgtop2-dev
    - librsvg2-dev
    - libsystemd-dev
    - libwnck-3-dev
    - libxml2-dev
    - make
    - mate-common
    - policykit-1
    - quilt
    - yelp-tools

  fedora:
    # Useful URL: https://src.fedoraproject.org/cgit/rpms/mate-system-monitor.git
    - autoconf-archive
    - clang
    - clang-analyzer
    - cppcheck-htmlreport
    - gcc
    - gcc-c++
    - dbus-glib-devel
    - desktop-file-utils
    - git
    - gtk3-devel
    - gtkmm30-devel
    - libgtop2-devel
    - librsvg2-devel
    - libwnck3-devel
    - libxml2-devel
    - make
    - mate-common
    - polkit-devel
    - redhat-rpm-config
    - systemd-devel

  ubuntu:
    - autopoint
    - autoconf-archive
    - clang
    - clang-tools
    - g++
    - git
    - libglib2.0-dev
    - libglibmm-2.4-dev
    - libgtk-3-dev
    - libgtkmm-3.0-dev
    - libgtop2-dev
    - librsvg2-dev
    - libsystemd-dev
    - libwnck-3-dev
    - libxml2-dev
    - make
    - mate-common
    - policykit-1
    - quilt
    - yelp-tools

variables:
  - CFLAGS="-Wall -Werror=format-security -Wredundant-decls"
  - 'CHECKERS="
    -enable-checker deadcode.DeadStores
    -enable-checker alpha.deadcode.UnreachableCode
    -enable-checker alpha.core.CastSize
    -enable-checker alpha.core.CastToStruct
    -enable-checker alpha.core.IdenticalExpr
    -enable-checker alpha.core.SizeofPtr
    -enable-checker alpha.security.ArrayBoundV2
    -enable-checker alpha.security.MallocOverflow
    -enable-checker alpha.security.ReturnPtrRange
    -enable-checker alpha.unix.SimpleStream
    -enable-checker alpha.unix.cstring.BufferOverlap
    -enable-checker alpha.unix.cstring.NotNullTerminated
    -enable-checker alpha.unix.cstring.OutOfBounds
    -enable-checker alpha.core.FixedAddr
    -enable-checker security.insecureAPI.strcpy"'

before_scripts:
  - if [ ${DISTRO_NAME} == "debian" ];then
  -     curl -Ls -o debian.sh https://github.com/mate-desktop/mate-dev-scripts/raw/master/travis/debian.sh
  -     bash ./debian.sh
  - fi
  - cd ${START_DIR}
  - '[ -f mate-common-1.23.3.tar.xz ] || curl -Ls -o mate-common-1.23.3.tar.xz http://pub.mate-desktop.org/releases/1.23/mate-common-1.23.3.tar.xz'
  - tar xf mate-common-1.23.3.tar.xz
  - cd mate-common-1.23.3
  - if [ ${DISTRO_NAME} == "debian" -o ${DISTRO_NAME} == "ubuntu" ];then
  -     ./configure --prefix=/usr --libdir=/usr/lib/x86_64-linux-gnu --libexecdir=/usr/lib/x86_64-linux-gnu
  - else
  -     ./configure --prefix=/usr
  - fi
  - make
  - make install

build_scripts:
  - ./autogen.sh --enable-compile-warnings=maximum
  - scan-build $CHECKERS ./configure --enable-compile-warnings=maximum
  - if [ $CPU_COUNT -gt 1 ]; then
  -     scan-build $CHECKERS --keep-cc -o html-report make -j $CPU_COUNT
  - else
  -     scan-build $CHECKERS --keep-cc -o html-report make
  - fi
  - if [ ${DISTRO_NAME} == "debian" ];then
  -     cppcheck --enable=warning,style,performance,portability,information,missingInclude .
  - fi

after_scripts:
  - if [ ${DISTRO_NAME} == "fedora" ];then
  -   cppcheck --xml --output-file=cppcheck.xml --enable=warning,style,performance,portability,information,missingInclude .
  -   cppcheck-htmlreport --title=${REPO_NAME} --file=cppcheck.xml --report-dir=cppcheck-htmlreport
  -   ./gen-index -l 20 -i https://github.com/${OWNER_NAME}/mate-icon-theme/raw/master/mate/16x16/apps/utilities-system-monitor.png
  - fi
  - make distcheck

releases:
  draft: false
  prerelease: false
  checksum: true
  file_glob: true
  files: mate-system-monitor-*.tar.xz
  github_release:
    tags: true
    overwrite: true
    base_version: 1.20.0
    notify_servers:
      - https://release.mate-desktop.org/release
