.TH "MATE-SYSTEM-MONITOR" "1" 
.SH "NAME" 
mate-system-monitor \(em view and control processes 
.SH "SYNOPSIS" 
.PP 
\fBmate-system-monitor\fR [\fB-s,\fP\fB\-\-show-system-tab\fP]  
.SH "mate-system-monitor" 
.PP 
The mate-system-monitor allows you to view and control the 
processes running on your system.  You can access detailed memory 
maps, send signals, and terminate the processes. 
.PP 
In addition, the mate-system-monitor provides an overall 
view of the resource usage on your system, including memory 
and CPU allocation. 
.SH "OPTIONS" 
.PP 
This program accepts all the standard MATE and GTK+
options, which follow the usual GNU command line syntax, with long 
options starting with two dashes ('\-').  In addition to those 
standard MATE options, the 
mate-system-monitor accepts the following options: 
.IP "\fB-s,\fP  \fB\-\-show-system-tab\fP         " 10 
Show the System tab. 
.SH "AUTHOR" 
.PP 
The mate-system-monitor was written by Kevin Vandersloot . 
.PP 
This manual page was written by Colin Walters walters@debian.org for 
the \fBDebian\fP system (but may be used by others).  Permission is 
granted to copy, distribute and/or modify this document under 
the terms of the GNU Free Documentation 
License, Version 1.1 or any later version published by the Free 
Software Foundation; with no Invariant Sections, no Front-Cover 
Texts and no Back-Cover Texts. 
